### ISSUE TITLE
uninitialized constant SafeTimeout::Timeout

### ISSUE THREAD

**Issue by djberg96** [david-mccullars/safe_timeout#2]
Hi,

I just tried safe_timeout and got this error, which is not the error I was expecting:

```
# safe_timeout_test.rb
require 'safe_timeout'

SafeTimeout.timeout(3){
  puts "Hello"
  sleep 5
}
```

Results:

```
>ruby safe_timeout_test.rb 
Hello
/Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/safe_timeout-0.0.4/lib/safe_timeout.rb:14:in `block in timeout': uninitialized constant SafeTimeout::Timeout (NameError)
    from safe_timeout_test.rb:5:in `call'
    from safe_timeout_test.rb:5:in `sleep'
    from safe_timeout_test.rb:5:in `block in <main>'
    from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/safe_timeout-0.0.4/lib/safe_timeout/spawner.rb:12:in `start'
    from /Users/dberger/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/safe_timeout-0.0.4/lib/safe_timeout.rb:15:in `timeout'
    from safe_timeout_test.rb:3:in `<main>'
```

**Comment by djberg96** [comment]
It looks like Timeout::Error is referenced, but not defined. A workaround is to require timeout first.

**Comment by david-mccullars** [comment]
Should be fixed now.  Thanks for the feedback.
